[package]
name = "winston_mongodb"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
logform = "0.3.1"
mongodb = "3.2.0"
serde = "1.0.217"
serde_json = "1.0.138"
tokio = "1.43.0"
winston_transport = "0.3.1"
